import { NextResponse } from 'next/server';
import { headers } from 'next/headers';
import { resolveStorefront } from '@/lib/api/storefront';
import { resolveTenantInfo } from '@/lib/tenant';

export async function GET() {
  const headersList = await headers();
  const host = headersList.get('host') || '';
  const slug = headersList.get('x-tenant-slug') || '';
  const protocol = host.includes('localhost') ? 'http' : 'https';
  const baseUrl = `${protocol}://${host}`;

  // Resolve store information
  const [resolution, tenantHost] = await Promise.all([
    resolveStorefront(slug),
    resolveTenantInfo(slug),
  ]);

  const storeName = resolution?.name || tenantHost?.name || 'Store';
  const storeDescription = `${storeName} is an e-commerce storefront powered by Mark8ly.`;

  const content = `# ${storeName}

> ${storeDescription}

## About This Store
${storeName} is an online retail store offering a curated selection of products. We focus on quality, value, and excellent customer service.

## Key Pages

### Public Pages (Indexable)
- ${baseUrl}/ - Homepage with featured products and promotions
- ${baseUrl}/products - Browse all products with filtering and sorting
- ${baseUrl}/products/{product-id} - Individual product details with specifications, pricing, and reviews
- ${baseUrl}/categories - Shop by product category
- ${baseUrl}/search?q={query} - Search products by keyword
- ${baseUrl}/about - About the store and company information
- ${baseUrl}/contact - Contact information and support

### Private Pages (Not Indexable)
These pages contain user-specific data and should not be crawled:
- /account/* - User account management
- /checkout/* - Checkout and payment flow
- /cart - Shopping cart
- /login, /register - Authentication pages

## Product Information
Each product page at ${baseUrl}/products/{product-id} includes:
- Product name and description
- Price and availability status
- High-quality product images
- Customer reviews and ratings
- Product specifications
- Related products

## Structured Data
All product pages include Schema.org ProductWithRating markup in JSON-LD format, providing:
- Product identification (name, SKU, brand)
- Pricing information
- Availability status
- Aggregate rating and review count
- Breadcrumb navigation

## API Information
This store does not provide a public API. All /api/* endpoints are for internal use only.

## Content Freshness
- Product catalog is updated in real-time
- Prices and availability are current
- Reviews are added by verified customers

## Crawling Guidelines
- Respect robots.txt directives
- Rate limit requests appropriately
- Focus on /products/ and /categories/ for product information
- Do not attempt to access authenticated pages

## Contact
For questions about this store or its content, please use the contact form at ${baseUrl}/contact

---
Generated by Mark8ly Storefront Platform
`;

  return new NextResponse(content, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=86400', // Cache for 24 hours
    },
  });
}
